name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker/build
    - name: Lint and unit tests
      run: make docker/tests
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
    - name: Run (KAP)
      run: docker run --name=hoysi -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} ${{ secrets.DOCKERHUB_IMAGE_VERSION }}
  # run-tryout:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
    # - name: Date
    #   run: date
  #   - name: Set timezone
  #     run: sudo timedatectl set-timezone "Europe/Madrid"
    # - name: Date
    #   run: date
    # - name: Print output
    #   run: docker logs hoysi
