name: Ejecución periódica

on:
  schedule:
    - cron: "50 08 * * 1-6"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Date
        run: date
      - name: Run (KAP)
        run: docker run --name=hoysi -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} ${{ secrets.DOCKERHUB_IMAGE_VERSION }}
      # - name: Set timezone
      #   run: sudo timedatectl set-timezone "Europe/Madrid"
      # - name: Date
      #   run: date
     # - name: Print output
      #  run: docker logs hoysi
      # - name: Run fitbot (WOD)
      #   run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"}\,\"1\":{\"time\":\"1700_60\"\,\"name\":\"OPEN\ BOX\"},\"2\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"},\"3\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"},\"4\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }}  pablobuenaposada/fitbot
