name: Ejecución periódica

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      # - name: Build docker image
      #   run: make docker/build
      - name: Date
        run: docker container ls
      - name: Date
        run: date
      - name: Run (OPEN BOX)
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1830\"\,\"name\":\"OPEN\ BOX\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} -e days-in-advance=2 pablobuenaposada/fitbot
      - name: Print output
        run: docker logs fitbot
      # - name: Run fitbot (WOD)
      #   run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"}\,\"1\":{\"time\":\"1700_60\"\,\"name\":\"OPEN\ BOX\"},\"2\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"},\"3\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"},\"4\":{\"time\":\"1900_60\"\,\"name\":\"OPEN\ BOX\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} -e days-in-advance=4 pablobuenaposada/fitbot
